### ISSUE TITLE
incorrect date without leading zero in .get('2016-1-17')

### ISSUE THREAD

**Issue by bencharb** [crsmithdev/arrow#292]
This is misleading. '2016-01-17' != '2016-1-17'

``` python

import arrow
import dateutil

withzero = '2016-01-17'
withoutzero = '2016-1-17'
assert dateutil.parser.parse(withzero) == dateutil.parser.parse(withoutzero)
assert arrow.get(withzero) != arrow.get(withoutzero)
```

**Comment by mattalytics** [comment]
Even more disturbingly:

```
arrow.get('2016/1/1').datetime == arrow.get('2016/1/10').datetime
```

!!!

**Comment by bencharb** [comment]
I'm startled that this basic parsing fails.

**Comment by philiptzou** [comment]
According to the document, `arrow.get` support the format "2016-01-17" is because it is an ISO-8601-formatted `str` <sup>[[doc:ArrowFactory]](http://arrow.readthedocs.org/en/latest/#arrow.factory.ArrowFactory)</sup>. According to RFC3339 which follows ISO-8601, the `date-month`, `date-mday`, `time-hour`, `time-minute` and `time-second` are all strict 2 digit chars<sup>[[rfc3339:sec5.6]](http://tools.ietf.org/html/rfc3339#section-5.6)</sup>.

So I'm afraid this might be `wontfix` and perhaps you could use more flexible way to parse that date string. For example:

```python
import arrow
arrow.parser.DateTimeParser().parse('2016-1-10', 'YYYY-M-D')
```

Or another solution here is we add another method to `DateTimeParser` which loosely parse string looks like ISO-8601 but not exactly is? Actually you can add such thing to your software easily. Just copy all the code of `DateTimeParser.parse_iso` and replace all MM to M, DD to D, HH to H, mm to m, and ss to s. Also don't forget the ones in `DateTimeParser.MARKERS`. And you got your own `parse_loose_iso` function.

**Comment by mattalytics** [comment]
Hi Philip,

I see. That is not unreasonable. However, if Arrow is to strictly
enforce the 2 digit month/day standard, perhaps a 1 digit day/month (e.g.
2010-1-1) should throw an error. Quietly transforming the date is a good
way to cause bugs in users' implementations.

Personally, I like the idea of arrow being a bit more flexible. Ease of
use is why I decided to try using arrow. Just my personal perspective.

Matt

**Comment by bencharb** [comment]
I'm with Matt, if the date string is invalid or ambiguous it ought to raise an exception. Thanks for your attention to this.

**Comment by philiptzou** [comment]
I'm  also with the idea of raising an exception, I think it is feasible. Btw, @bencharb I think you are still need to parse the non-standard string. I know Arrow is great but it may be not the best choice for your needs. AFAIK [parsedatetime](https://github.com/bear/parsedatetime) is good at parsing human-readable datetime strings. So you may want to try that instead.

**Comment by bencharb** [comment]
That works, thanks, @philliptzou.

**Comment by balihoo-gens** [comment]
I'd like to reference issue #267 here as it points out a similar case of defaulting to 1 when parsing fails (instead of an exception). Example:

```
>>> arrow.get("2016-09-31")
<Arrow [2016-09-01T00:00:00+00:00]>
```

One would hope for an exception like dateutils.parser.parse gives:

```
>>> dateutil.parser.parse("2016-09-31")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "dateutil/parser.py", line 577, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
```

Currently, my workaround is to not have `arrow.get` do any parsing, using `dateutil` instead:
`arrow.get(dateutil.parser.parse(date_string))`

**Comment by andrewelkins** [comment]
Will be handled by #91
