### ISSUE TITLE
Having issue using range to iterate through dates

### ISSUE THREAD

**Issue by jmagana2000** [crsmithdev/arrow#298]
Trying to use Arrow to iterate through a range of dates and when I do I get the following error:
```shell
for r in arrow.Arrow.range('days',start=ts1,end=insert_ts,limit=100):
File "/usr/local/lib/python2.7/site-packages/arrow/arrow.py", line 209, in range
    _, frame_relative, relative_steps = cls._get_frames(frame)
File "/usr/local/lib/python2.7/site-packages/arrow/arrow.py", line 872, in _get_frames
    raise AttributeError()
AttributeError
```
Here is the code:
```python
ts1 =  arrow.Arrow.strptime(ts.encode('utf-8'),'%Y-%m-%d %H:%M:%S.%f')
next_ts = ts1.replace(days=1)
for r in arrow.Arrow.range('days',start=ts1,end=insert_ts,limit=100):
    print repr(r)
```
Should iterate from "2013-04-24 23:59:59.976345" to current date.

**Comment by jaapz** [comment]
Looks like `Arrow._get_frames` only checks the first argument in the non-plural list. So if you use `Arrow.range('day')` instead of `Arrow.range('days')` your code should work.

However, I think it would be nice if you could use both `days` and ` day` in this case, so maybe a check for the plural in `_get_frames` can be added. If you want, a PR would probably be appreciated by the author.

**Comment by jmagana2000** [comment]
Thanks for the response.  Just did a while loop and that seems to work.

ts1 =  arrow.Arrow.strptime(ts.encode('utf-8'),'%Y-%m-%d %H:%M:%S.%f')
next_ts = ts1.replace(days=1)
while ts1 <= insert_ts:
    ts1_str = ts1.format('YYYY-MM-DD HH:mm:ss.SSSSSS')
    ts2_str = next_ts.format('YYYY-MM-DD HH:mm:ss.SSSSSS')
    ...
    ts1 = ts1.replace(days=1)
    next_ts = ts1.replace(days=1)

**Comment by JunhwanK** [comment]
I will work on adding a check for the plural in _get_frames function
