### ISSUE TITLE
Daylight savings related bug

### ISSUE THREAD

**Issue by vmp2575** [crsmithdev/arrow#333]
`utc=arrow.get(1414906200)
`
`print utc.to('local').datetime
`
2014-11-02 00:30:00-05:00

`print utc.replace(hours=+1).to('local').datetime
`
2014-11-02 01:30:00-06:00      <<<<<<<< It should be 2014-11-02 01:30:00-**05:00**

`print utc.replace(hours=+2).to('local').datetime
`
2014-11-02 01:30:00-06:00

**Comment by LuisUrrutia** [comment]
You should add hours after to local, in this way:

```
utc=arrow.get(1414906200)
>>> print utc.to('local').datetime
2014-11-02 02:30:00-03:00

>>> print utc.to('local').replace(hours=+1).datetime
2014-11-02 03:30:00-03:00
```

**Comment by vmp2575** [comment]
Nope, still doesn't work correctly. This time (1414906200) is specific for US/Central timezone, it is before switching from Daylight saving back to standard.

`>>> utc=arrow.get(1414906200)`
`>>> print utc.to('US/Central').datetime`
2014-11-02 00:30:00-05:00
`>>> print utc.to('US/Central').replace(hours=+1).datetime `
2014-11-02 01:30:00-06:00        <<<<<<< Should be 2014-11-02 01:30:00-**05:00**
`>>> print utc.to('US/Central').replace(hours=+2).datetime `
2014-11-02 02:30:00-06:00        <<<<<<< Should be 2014-11-02 **01**:30:00-06:00

**Comment by pganssle** [comment]
@vmp2575 I'm fairly sure this is an upstream bug in dateutil. A fix is already committed in dateutil/dateutil#264, which should be finished and accepted this weekend, if all goes well.

The fix will be released as part of dateutil version 2.6.0, which I'm unofficially hoping to release on or before July 1st.

A workaround you can use now is to use the current master branch of dateutil (which already has a fix committed in dateutil/dateutil#225 for `tzfile`, so if you specify `'US/Central'` or `'US/Eastern'` or what have you rather than `'local'` you should be good). I don't know if it's possible to use `pytz` with `arrow`, but in the mean time, `pytz` time zones do handle this "correctly" (see the extensive discussion in dateutil/dateutil#225 as to why this is in quotes).

**Comment by vmp2575** [comment]
Thank you!
BTW, looks like pytz works just fine.

`utc=arrow.get(1414906200)`
`>>> print utc.replace(hours=+0).to(pytz.timezone('US/Central')).datetime`
2014-11-02 00:30:00-05:00
`>>> print utc.replace(hours=+1).to(pytz.timezone('US/Central')).datetime`
2014-11-02 01:30:00-05:00
`>>> print utc.replace(hours=+2).to(pytz.timezone('US/Central')).datetime`
2014-11-02 01:30:00-06:00
`>>> print utc.replace(hours=+3).to(pytz.timezone('US/Central')).datetime`
2014-11-02 02:30:00-06:00`

**Comment by andrewelkins** [comment]
Thanks for the comments! Closing
