### ISSUE TITLE
daylight savings time and 'ceil()'

### ISSUE THREAD

**Issue by rotten** [crsmithdev/arrow#376]
When the ceiling function is called across a daylight savings time change, the offset is not adjusted:

This is wrong:
```
>>> arrow.get('2016-11-06').to('America/New_York').ceil('day')
<Arrow [2016-11-05T23:59:59.999999-04:00]>

```

This is right:
```
>>> arrow.get('2016-11-06 12:00').to('America/New_York').ceil('day')
<Arrow [2016-11-06T23:59:59.999999-05:00]>
```

floor() works though:
```
>>> arrow.get('2016-11-06 12:00').to('America/New_York').floor('day')
<Arrow [2016-11-06T00:00:00-04:00]>
```

**Comment by ajdidonato7** [comment]
I am beginning to look into this issue

**Comment by jadchaar** [comment]
@ajdidonato7 sounds good. The fold attribute provided by `dateutil` may be useful here to detect a DST transition (ref: https://github.com/crsmithdev/arrow/issues/488).

**Comment by ajdidonato7** [comment]
I will have a pull request for this change in the next few days

**Comment by ajdidonato7** [comment]
I think what was believed to be a bug was actually expected behavior. 

The user made the assumption that '2016-11-06 00:00' should not ceil() to <Arrow [2016-11-05T23:59:59.999999-04:00]> but in reality they are dealing with UTC time, so '2016-11-06 00:00' is actually '2016-11-05 08:00' in the 'America/New_York' time zone (which would ceil() to that value). I have produced output to show that the correct ceil behavior is exhibited around the true EST date change, which occurs at 4am UTC the following day.

`arrow.get('2016-11-06 03:59').to('America/New_York').ceil('day')`
`<Arrow [2016-11-05T23:59:59.999999-04:00]>`

`arrow.get('2016-11-06 04:00').to('America/New_York').ceil('day')`
`<Arrow [2016-11-06T23:59:59.999999-05:00]>`

Thoughts on this? @jadchaar @systemcatch I can produce test cases that confirm this if it is correct.
