### ISSUE TITLE
Drop support for Python 2.6?

### ISSUE THREAD

**Issue by cclauss** [crsmithdev/arrow#426]
https://travis-ci.org/crsmithdev/arrow/jobs/212040401#L116 says: _DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6_

Python 2.6 End of Life was in 2013... https://docs.python.org/devguide/index.html#branchstatus

Should arrow drop support for Python 2.6?

**Comment by hugovk** [comment]
Drop it.

* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by hugovk** [comment]
Here's the pip installs for arrow from PyPI for the last month:
```
$ pypinfo --percent --pip arrow pyversion
python_version percent download_count
-------------- ------- --------------
2.7              59.8%        880,090
3.6              35.4%        520,727
3.4               2.5%         36,115
3.5               2.2%         32,627
3.3               0.0%            616
2.6               0.0%            534
3.7               0.0%            386
3.2               0.0%              7
None              0.0%              1

```
