### ISSUE TITLE
arrow.parser.ParserError: Could not parse timezone expression "EDT"

### ISSUE THREAD

**Issue by knodalyte** [crsmithdev/arrow#435]

**Comment by rhurkes** [comment]
After running into this myself, I decide to dig a little. This is being raised out of ```TzinfoParser.parse``` as ```dateutil.tz.gettz()``` doesn't return anything for the string ```EDT``` (or any of the commonly-used and similarly-named DST timezones).

```gettz``` looks in a few different places on non-Windows machines, namely in ```/usr/share/zoneinfo```. That directory is populated by timezone compilers like [zic](https://www.freebsd.org/cgi/man.cgi?query=zic&sektion=8), but on every OSX/Linux machine I've checked, none of them have ```EDT``` - it's always just the proper name ```EST5EDT```. There's a format definition in the [IANA database](https://www.iana.org/time-zones) that would allow for reconciliation of the "common" name with the "proper" name, but this doesn't seem to be done at the system level.

My opinion on how this should be supported in a timezone-aware library has become even muddier after digging. At least for my case, it's easy enough to replace instances of the common formatted name with their respective IANA name as a workaround.

**Comment by pganssle** [comment]
@rhurkes @knodalyte The reason for this is that, essentially, 3-letter timezone abbreviations are not unique, so there's not enough context to determine what they are, and generally you should *not* count on being able to go from a 3-letter abbreviation to a time zone. Consider "CST", which could be China Standard Time, Cuba Standard Time, Central Standard Time. I consider the fact that EST is in the IANA database a bit of an attractive nuisance, because it leads to this sort of problem.

`dateutil.parser.parse` takes an argument `tzinfos` that lets you specify the specific way you want to disambiguate the 3- and 4-letter abbreviations that are common. I am not familiar with the way that `arrow` handles it, but I assume it has a way to pass that information through to `dateutil`. Here's how you'd achieve what you want in `dateutil`:

```python
from dateutil.parser import parse
from dateutil.tz import gettz
EASTERN = gettz('US/Eastern')
dt = parse('2014-05-05 12:45:30 EDT', tzinfos={'EDT': EASTERN, 'EST': EASTERN)
```

**Comment by knodalyte** [comment]
I had done some more looking after submitting this issue, and it seems that the Python standard libraries are "broken" with respect to handling an abbreviation like EDT. I ended up coding a workaround that handles my use case, which is US timezones exclusively.  I just figured that a utility like arrow should handle it automagically, but if there is no unambiguous canonical source for this data, that certainly makes it pretty hard to come up with a consistent solution.

**Comment by pganssle** [comment]
@knodalyte That's essentially what *should* be happening. In this case, at the moment `EDT` is more or less a unique identifier, so technically you *could* uniquely map it to Eastern time, but I think it's better to fail *early* with respect to 3-digit identifiers, because otherwise you might test with respect `EDT`, then when you get something like `CDT` and expect it to just work correctly, it will fail and you have to add in a whole bunch of completely separate logic for that - plus what happens if a new time zone using `EDT` is created and your old logic stops working?

The approach where you provide the context (i.e. "if you see `EDT`, in this case it means "US Eastern Time Zone") is the right way to go.

**Comment by systemcatch** [comment]
@pganssle explained it really well, we should make this more explicit in the docs.
