### ISSUE TITLE
Failed conversion to own time zone

### ISSUE THREAD

**Issue by agroce** [crsmithdev/arrow#492]
import arrow

val0 = 1
zone0 = 'Europe/Rome'
time1 = arrow.get(val0)
time0 = time1.to(zone0)
time1 = time1.replace(year=val0)
time2 = time1.replace(tzinfo=zone0)
print time2
print time2.tzinfo
time1 = time2.to(zone0)

This fails with:

0001-01-01T00:00:01+01:00
tzfile('/usr/share/zoneinfo/Europe/Rome')
Traceback (most recent call last):
  File "arrowtest.py", line 11, in <module>
    time1 = time2.to(zone0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arrow/arrow.py", line 510, in to
    dt = self._datetime.astimezone(tz)
OverflowError: date value out of range

Generated by random testing using TSTL (https://github.com/agroce/tstl/tree/master/examples/arrow)

**Comment by ifduyue** [comment]
```pyhton
In [19]: arrow.get(1)
Out[19]: <Arrow [1970-01-01T00:00:01+00:00]>

In [20]: a1 = arrow.get(1)

In [21]: a1
Out[21]: <Arrow [1970-01-01T00:00:01+00:00]>

In [22]: a2 = a1.to('Europe/Rome')

In [23]: a2
Out[23]: <Arrow [1970-01-01T01:00:01+01:00]>

In [24]: a3 = a1.replace(year=1)

In [25]: a3
Out[25]: <Arrow [0001-01-01T00:00:01+00:00]>

In [26]: a4 = a1.replace(tzinfo='Europe/Rome')

In [27]: a4
Out[27]: <Arrow [1970-01-01T00:00:01+01:00]>

In [28]: a4.tzinfo
Out[28]: tzfile('/usr/share/zoneinfo/Europe/Rome')

In [29]: a4.to('Europe/Rome')
Out[29]: <Arrow [1970-01-01T00:00:01+01:00]>
```

Woks for me. I am using arrow 0.10.0

**Comment by agroce** [comment]
On the pip installed 0.12.0 on OS X sierra, the file above indeed produces the exception claimed.

**Comment by agroce** [comment]
Python 2.7.13

**Comment by pganssle** [comment]
@agroce You started with the minimum possible date `datetime(1, 1, 1)`, plus one second, expressed in a timezone where the UTC offset is `+00:50`. Then you tried to convert it to UTC, e.g. you tried to subtract 50 minutes from 1 second after the smallest possible date that you can represent in Python. An overflow error is what you'd expect. This is not a bug.

**Comment by agroce** [comment]
Yeah, the question is that it seems invalid before the last step.  Why does the first .to work?  The second looks like a no-op?

**Comment by pganssle** [comment]
@agroce For two reasons:

1. `arrow.get(1)` interprets `1` as an epoch time, e.g. `1970-1-1T00:00:01`
2. `arrow.get(1)` returns an `Arrow` in UTC and going *to* `Europe/Rome` involves *adding* an hour.

If you inspect each item as you go along you can see what is happening.

**Comment by pganssle** [comment]
Oh, I see what you mean. There was a lot of random complicated stuff going on in your example, here's a cleaner one:

```python
import arrow

dt = arrow.get('0001-01-01').replace(tzinfo='Europe/Rome')
dt.to('Europe/Rome')
```

The problem here is that an intermediate stage in time zone conversion somewhat unavoidably involves a round trip from zone 1 -> UTC -> zone 2. And the problem is that the `UTC` version of this datetime is out of range.

You can skip this if `zone1 is zone2`, but that's not currently true for the way `arrow` constructs time zones. Even if it *were* true, you'd still have the same "absurd" result if you were to try to convert from `Europe/Rome` to `Asia/Shanghai`, even though both the `Europe/Rome` and `Asia/Shanghai` zones have valid representations of that datetime anyway.

In any case, I don't really think it's worth "fixing" (to the extent that you even can), since these political zones like `Europe/Rome` and `Asia/Shanghai` are modern inventions, so applying them to ancient times like that is a weird anachronism.
