### ISSUE TITLE
Display stdlib errors on Travis run

### ISSUE THREAD

**Issue by systemcatch** [crsmithdev/arrow#589]
So I figured out how we can display `stdlib` errors on a Travis run: we can run `nose` as a module and set a flag (`-Wd`)for Python to display all warnings.

I was thinking we could make a separate target for testing the dev releases:
```make
test-dev:
	rm -f .coverage
	. local/bin/activate && local/bin/python3 -Wd -m nose
```

_Originally posted by @jadchaar in https://github.com/crsmithdev/arrow/pull/585#issuecomment-493787621_

**Comment by jadchaar** [comment]
Gonna try and tackle this when I get some free time :)

**Comment by jadchaar** [comment]
I added this to the Makefile in the latest PR so it can be run before future Python releases going forward. I am not putting it in Travis because the only warnings emitted are by the dated `nose` and by a deprecation warning emitted by `arrow` itself. I think adding it to Travis could introduce extra clutter and confusion :).
