### ISSUE TITLE
Specify number of subsecond tokens to parse

### ISSUE THREAD

**Issue by systemcatch** [crsmithdev/arrow#627]
Currently when parsing strings with a subsecond component the following works.

```shell
>>> arrow.get("2013-02-09T11:09:23.345678", "YYYY-MM-DDTHH:mm:ss.SSS")
<Arrow [2013-02-09T11:09:23.345678+00:00]>
```

But it doesn't actually matter how many `S` tokens you supply, all the subseconds are parsed.
```shell
>>> arrow.get("2013-02-09T11:09:23.345678", "YYYY-MM-DDTHH:mm:ss.S")
<Arrow [2013-02-09T11:09:23.345678+00:00]>
```

We thought about removing the ability to pass multiple S tokens in 0.15.0 but decided to avoid changing anything in that release. The formatter will let you specify how ever many S tokens you need.

Community thoughts would be useful here.

**Comment by sidshrivastav** [comment]
Please find PR[](https://github.com/crsmithdev/arrow/pull/685).

**Comment by jadchaar** [comment]
@systemcatch I am not sure what the best interface for this would be. If we deprecate the functionality of all S's being the same as a single S, we would need to provide a deprecation warning because some people may rely on the old functionality. I think an alternative solution could be to introduce a second subsecond token like "S{1,2,3,4,5,6}" to specify the number of digits to parse.

**Comment by jadchaar** [comment]
@systemcatch and I decided that it is best to close this issue for now to focus on more important issues in Arrow :).
