### ISSUE TITLE
Error parsing date with over 999999 in microseconds

### ISSUE THREAD

**Issue by matthewdooler** [crsmithdev/arrow#636]
I get the following error if I try to parse a date with a timestamp that has over 6 digits in the fractional second and is also over 999999:
```
microsecond must be in 0..999999
```

Example inputs: `2019-08-14T15:37:11.9999995+01:00`, `2019-08-14T15:37:11.9999996+01:00` but *not* `2019-08-14T15:37:11.9999994+01:00`

Arrow version: 0.14.5
Python version: 3.7.3

Seems related to https://github.com/crsmithdev/arrow/issues/341 but not quite the same issue.

**Comment by matthewdooler** [comment]
This is my current workaround as I don't need the precision - I just need to be able to accept the date and do a rough calculation:
```
s = "2019-08-14T15:37:11.9999995+01:00"
bad_millis = [".9999995", ".9999996", ".9999997", ".9999998", ".9999999"]
for bad_milli in bad_millis:
    s = s.replace(bad_milli, ".9999994")
t = arrow.get(s)
```

**Comment by jadchaar** [comment]
Hey @matthewdooler, thanks for the bug report. This is due to the rounding logic here: https://github.com/crsmithdev/arrow/blob/master/arrow/parser.py#L232.

We need to add a conditional to account for the case in which it overflows from 999999 to 1000000 to zero out the subseconds and increment the seconds.

If you'd like to take a whack at this issue, feel free to submit a PR. Any help is appreciated :).

**Comment by matthewdooler** [comment]
Have raised a PR if anyone could take a look :)

https://github.com/crsmithdev/arrow/pull/643
