### ISSUE TITLE
AttributeError: unknown attribute: "hours"

### ISSUE THREAD

**Issue by jsale** [crsmithdev/arrow#638]
I just installed arrow and ran the first example. Here's my output. I get the same error for 'days'. Murphy is alive and well this morning, I guess. :-)

```shell
$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
\>>> import arrow
\>>> utc = arrow.utcnow()
\>>> utc
<Arrow [2019-08-15T13:23:07.912369+00:00]>
\>>> utc = utc.replace(hours=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jsale/anaconda3/lib/python3.7/site-packages/arrow/arrow.py", line 590, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "hours"
```

**Comment by jadchaar** [comment]
Hey @jsale, this is due to a recent deprecation (we forgot to update the docs). The plural attributes have been moved to the ‘shift’ function. This was done to prevent hard-to-find bugs since the functionality of passing ‘hour’ and ‘hours’ to ‘replace’ had completely different effects.

I have put in a PR to update the docs to reflect the recent deprecation: https://github.com/crsmithdev/arrow/pull/637.

‘>>> utc = utc.shift(hours=-1)’ should work!

Let me know if this resolves the issue you are having :).

**Comment by jsale** [comment]
Thank you very much!
