### ISSUE TITLE
More formats of time

### ISSUE THREAD

**Issue by yyan1998** [crsmithdev/arrow#681]
Can add more format to parse such as YYYY/M. For each type of format, it's better to allow single digits of months/dates and missing dates. (I got ParserError when I tried to parse the time on the bibs of scholars on Google scholar)

**Comment by systemcatch** [comment]
Hi @yyan1998, you mean something like this?

```shell
(arrow) chris@ThinkPad:~/arrow$ python
Python 3.7.4 (default, Sep 19 2019, 11:01:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.15.2'
>>> arrow.get("1999/8", "YYYY/M")
<Arrow [1999-08-01T00:00:00+00:00]>
```

**Comment by jadchaar** [comment]
Hey @yyan1998, like @systemcatch said, you can easily parse this by passing the format string to `arrow.get()`. If you still have any questions, or are unable to get this to work, please let us know. For now, I am closing this issue.

**Comment by zaraken** [comment]
I want to piggyback on this issue since I think my question is somewhat the same.
Why is it that `arrow.get` can parse '1970-01-01T00:00:00' but not '1970-1-1T00:00:00'
Or to state my question differently how would I define a format string that can match both formats?
For now I fell back to using `arrow.Arrow.strptime()` with format '%Y-%m-%dT%H:%M:%S' which can parse both.
Sure, I can manually try both formats with arrow get but then I'm missing on the 'ease-of-use' of arrow that I'm used to and this is not a case that is uncommon, nor are the time strings ambiguous, or are they ?

**Comment by jadchaar** [comment]
Hey @zaraken, Arrow v0.14.7 and below will not parse YYYY-M-D because the method was originally focused solely on parsing [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) date and time strings.

If you upgrade to Arrow v0.15.0 and above (run `pip install -U arrow`), Arrow will parse YYYY-M-D properly since we now test against commonly used, non-ISO 8601 date and time strings as well:

```shell
venv ❯ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.15.2'
>>> arrow.get("1970-1-1T00:00:00")
<Arrow [1970-01-01T00:00:00+00:00]>
```

As for testing against multiple formats, you can pass in multiple format strings to test against in a list as follows:

```shell
venv ❯ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.15.2'
>>> datetime_strings = ["1970-01-01T00:00:00", "1970-1-1T00:00:00"]
>>> for dt_str in datetime_strings:
...     arrow.get(dt_str, ["YYYY-MM-DDTHH:mm:ss", "YYYY-M-DTHH:mm:ss"])
...
<Arrow [1970-01-01T00:00:00+00:00]>
<Arrow [1970-01-01T00:00:00+00:00]>
```
