### ISSUE TITLE
`.humanize()` leads to wrong result with `datetime.date`

### ISSUE THREAD

**Issue by gustavoip** [crsmithdev/arrow#697]
I'm using `arrow` 0.15.2.

```
>>> import datetime, arrow
>>> yesterday = datetime.datetime.now()-datetime.timedelta(1)
>>> yesterday_date = yesterday.date()
>>> arrow.get(yesterday_date).humanize()
'2 days ago'
```
As far as I know yesterday was 1 day ago haha. Is this the expected behavior?

**Comment by jadchaar** [comment]
Hmm at first I thought that this may be related to the changes in 0.15.0 to add the week granularity (https://github.com/crsmithdev/arrow/pull/642/files), but it seems that this issue is present in 0.14.7 as well. @systemcatch any ideas? I can investigate this further after my exams.

**Comment by systemcatch** [comment]
```shell
>>> yesterday = datetime.datetime.now()-datetime.timedelta(1)
>>> yesterday
datetime.datetime(2019, 11, 7, 17, 17, 43, 979355)
>>> yesterday_date = yesterday.date()
>>> yesterday_date
datetime.date(2019, 11, 7)
>>> arrow.get(yesterday_date).humanize()
'2 days ago'
>>> arrow.get(yesterday).humanize()
'a day ago'
```
So it works correctly with the `datetime` object but not with the `date`. Further investigation needed.

**Comment by jadchaar** [comment]
Hmm it means we have to tweak some parameters to get a good middle ground. Will require a bit more investigation.

**Comment by andrewchouman** [comment]
Can I look into this? @jadchaar

**Comment by jadchaar** [comment]
Yes for sure @andrewchouman! Go for it and feel free to ask us any questions.

**Comment by skrakowi** [comment]
Hello @jadchaar I am working with @andrewchouman on this issue. I noticed that the thresholds/parameters for deciding whether a timestamp is one day or multiple days ago is not exact. In other words, two timestamps can only be one day apart if they are within 22 - 36 hours of each other. However, it is very possible for two timestamps to be within 1 hour or even 47 hours of each other and still be one day apart. This can be fixed by checking the "day" attribute of the datetime objects throughout the function. If you are ok with this solution, I can go ahead and work on it.

**Comment by jadchaar** [comment]
@skrakowi that is most likely because below 22 hours, we use "hour ago" granularity as follows:

```shell
venv ❯ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> earlier = arrow.utcnow().shift(hours=-20)
>>> earlier.humanize()
'20 hours ago'
>>> earlier = arrow.utcnow().shift(hours=-21)
>>> earlier.humanize()
'21 hours ago'
>>> earlier = arrow.utcnow().shift(hours=-22)
>>> earlier.humanize()
'a day ago'
```

Also, for the UTC question, it seems that the `other` object is being adjusted to the `tzinfo` (timezone info) of the Arrow instance that `humanize` is being called on: https://github.com/crsmithdev/arrow/blob/master/arrow/arrow.py#L892. Is this the portion of the code that you were referencing?

**Comment by skrakowi** [comment]
@jadchaar yes this is what I was referring to. After running and testing the code, it appears that line 892 does not change the utc current time to the local time. It takes the value of the utc current time (for example 19:02) and the local time zone becomes the property of the dt variable. This means that (assuming you are in the Eastern time zone) the difference between the dt and self._datetime will be 5 hours more than the difference in time between the self._datetime and the true current time. If my explanation does not make sense, please let me know and I can elaborate.

Also, the reason that the example above does not work is because when a datetime object has only a date defined (no time defined), the default time is set to 00:00:00. This datetime is being compared to the current date and current time. If it is late enough in the day, the difference between these two datetimes is greater than 129,600 so the program classifies the input as '2 days ago' (see line 936 to see the code I am talking about).

My suggestion for this fix involves 2 steps:
1. Correct the dt variable so that it gets the current time of the local time zone
2. As detailed above, check the date of the datetime objects (if the two differences are within 47 hours of each other) to see which day it corresponds to (either 'a day ago' or '2 days ago').

Please let me know how this sounds. I will start working on this fix now!
